services:
  igridmq:
    container_name: igridmq
    hostname: igridmq
    build: .
    restart: unless-stopped
    ports:
    - '1883:1883'
    - '8080:8080'
    depends_on:
      - mosquitto
    networks:
      - igrid-base-net
  mosquitto:
    container_name: mosquitto
    hostname: mosquitto
    image: library/eclipse-mosquitto:1.6
    restart: unless-stopped
    ports:
      - 1884
      - 8888
    volumes:
      - ./mosquitto/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
    networks:
      - igrid-base-net
volumes:
  mosquitto-logs:
  mosquitto-conf:
  mosquitto-data:
networks:
  igrid-base-net: