services:
  igridmq:
    container_name: igridmq
    hostname: igridmq
    build: .
    restart: unless-stopped
    ports:
    - '1883:1883'
    - '8080:8080'
    depends_on:
      - mosquitto
    networks:
      - igrid-base-net
  mosquitto:
    container_name: mosquitto
    hostname: mosquitto
    image: library/eclipse-mosquitto:1.6
    restart: unless-stopped
    ports:
      - 1884
      - 8888
    volumes:
      - ./mosquitto/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
    networks:
      - igrid-base-net
  postges:
    container_name: postgres
    image: postgres
    restart: on-failure
    ports:
      - '5432:5432'
    networks:
      - igrid-base-net
    environment:
      POSTGRES_PASSWORD: ${BP_POSTGRES_PASSWORD}
      POSTGRES_USER: ${BP_POSTGRES_USER}
      POSTGRES_DB: ${BP_POSTGRES_DB}
    volumes:
      - registry-postgres-volume:/var/lib/postgresql/data
volumes:
  mosquitto-logs:
  mosquitto-conf:
  mosquitto-data:
  registry-postgres-volume:
networks:
  igrid-base-net: